apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  KAFKA_URL: kafka-release.default.svc.cluster.local:9092
  KAFKA_TOPIC: location
metadata:
  name: db-env