apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-consumer-kafka
  name: udaconnect-location-consumer-kafka
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: udaconnect-location-consumer-kafka
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-consumer-kafka
  name: udaconnect-location-consumer-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-consumer-kafka
  template:
    metadata:
      labels:
        service: udaconnect-location-consumer-kafka
    spec:
      containers:
      - image: romran/udaconnect-location-consumer-kafka:latest
        name: udaconnect-location-consumer-kafka
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always