apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-producer-grpc-kafka
  name: udaconnect-location-producer-grpc-kafka
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30010
  selector:
    service: udaconnect-location-producer-grpc-kafka
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-producer-grpc-kafka
  name: udaconnect-location-producer-grpc-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-producer-grpc-kafka
  template:
    metadata:
      labels:
        service: udaconnect-location-producer-grpc-kafka
    spec:
      containers:
      - image: romran/udaconnect-location-producer-grpc-kafka:latest
        name: udaconnect-location-producer-grpc-kafka
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always