namespace:
  name: sandbox
replicaCount: 1
containerPort: 3111
service:
  port: 4111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP
image:
  repository: romran/techtrends 
  tag: latest
  pullPolicy: IfNotPresent
readinessProbe:
  path: /healthz
  port: 3111
livenessProbe:
  path: /healthz
  port: 3111
resources:
  requests:    
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
    
