namespace:
  name: prod
replicaCount: 5
image:
  pullPolicy: Always
service:
  port: 7111
resources:
  requests:    
    cpu: "350m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
    