apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    #Standout Suggestion 3: Helm chart conditionals
    {{ if .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    {{ else }}
    targetPort: {{ .Values.service.port }}
    {{ end }}
  selector:
    app: techtrends
    tag: latest
  type: {{ .Values.service.type }}